### ISSUE TITLE
Error in authorize API method

### ISSUE THREAD

**Issue by noglance** [kkamkou/ZF-Vkontakte-SDK#4]
$api->authorize($code);

returns 401 error at 124 line

object(Exception)#101 (7) { ["message":protected]=> string(351) "Request failed(401): Unauthorized at GET

**Comment by kkamkou** [comment]
This message means you use an invalid code for the authorization. The authorization link returns a use-only-once code.

**Comment by kkamkou** [comment]
@noglance I have to close this ticket. It looks like a problem on your side. Please, post a code piece if needed.
